#
# Docker file for AppStream Generator CI tests
#
FROM registry.fedoraproject.org/fedora:rawhide

# prepare
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-rpm.sh /build/ci/
RUN chmod +x /build/ci/install-deps-rpm.sh && /build/ci/install-deps-rpm.sh

# install 3rd-party stuff
COPY ci-install-extern.sh /build/ci/
RUN chmod +x /build/ci/ci-install-extern.sh && /build/ci/ci-install-extern.sh

# finish
WORKDIR /build
