#
# Docker file for AppStream Generator CI tests
#
FROM debian:testing

# prepare
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-deb.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb.sh && /build/ci/install-deps-deb.sh

# install 3rd-party stuff
COPY ci-install-extern.sh /build/ci/
RUN chmod +x /build/ci/ci-install-extern.sh && /build/ci/ci-install-extern.sh

# finish
WORKDIR /build
